### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by VincentRochet** [ghorsey/OpenGraph-Net#20]
**Describe the bug**
Not a bug technically speaking but I'm using OpenGraph 3.2.3 in a .NET Core 2.2 project, works well while on the dev pcs (Win2012, VisualStudio 20147). However, when published on our web server, it fails to find the DLL.
`2020-06-17 17:08:43.904 +02:00	[ERR]		b8d479ce-f635-4fd9-a4e3-87892fdaf998	Something went wrong: System.IO.FileNotFoundException: Could not load file or assembly 'OpenGraphNet, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'OpenGraphNet, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'
   at FlairAPI.Controllers.v1.BlackListController.GetDataFromUrl(String base64Url)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at FlairAPI.Controllers.v1.BlackListController.GetDataFromUrl(String base64Url)
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at FlairAPI.Middlewares.GlobalExceptionMiddleware.InvokeAsync(HttpContext httpContext)
`
I checked on de deployment folder and the DLL is there, as well as the HtmlAgilityPack.dll
Any idea ? If this is the wrong place for this kind of question, feel free to close this.

**Comment by VincentRochet** [comment]
Forget it

**Comment by ghorsey** [comment]
@VincentRochet  Hey... Sorry I didn't respond to this earlier... the day job has been crazy... Were you able to solve this?

**Comment by VincentRochet** [comment]
Yep it was not because of the dll ;-) just a "real" deployment issue
The dll works perfrectly, thanks
